commodity_dict = {
    '0577400': 'Amêndoas, Base Descascada',
    '0011000': 'Número de Animais, Gado',
    '0013000': 'Número de Animais, Suínos',
    '0574000': 'Maçãs, Frescas',
    '0430000': 'Cevada',
    '0579305': 'Cerejas (Doces e Azedas), Frescas',
    '0711100': 'Café, Verde',
    '0440000': 'Milho',
    '2631000': 'Algodão',
    '0230000': 'Laticínios, Manteiga',
    '0240000': 'Laticínios, Queijo',
    '0224400': 'Laticínios, Leite em Pó Integral',
    '0223000': 'Laticínios, Leite, Fluidos',
    '0224200': 'Laticínios, Leite, Desnatado em Pó',
    '0572220': 'Toranjas, Frescas',
    '0575100': 'Uvas, Mesa Frescas',
    '0572120': 'Limões/Limas, Frescos',
    '0813700': 'Farinha de Coco',
    '0813300': 'Farinha de Semente de Algodão',
    '0814200': 'Farinha de Peixe',
    '0813800': 'Farinha de Amêndoa de Palma',
    '0813200': 'Farinha de Amendoim',
    '0813600': 'Farinha de Colza',
    '0813100': 'Farinha de Soja',
    '0813101': 'Farinha de Soja (Local)',
    '0813500': 'Farinha de Semente de Girassol',
    '0111000': 'Carne, Bovina e Vitela',
    '0115000': 'Carne, Frango',
    '0113000': 'Carne, Suína',
    '0459100': 'Milheto',
    '0459900': 'Grãos Diversos',
    '0452000': 'Aveia',
    '4242000': 'Óleo de Coco',
    '4233000': 'Óleo de Semente de Algodão',
    '4235000': 'Óleo de Oliva',
    '4243000': 'Óleo de Palma',
    '4244000': 'Óleo de Amêndoa de Palma',
    '4234000': 'Óleo de Amendoim',
    '4239100': 'Óleo de Colza',
    '4232000': 'Óleo de Soja',
    '4232001': 'Óleo de Soja (Local)',
    '4236000': 'Óleo de Semente de Girassol',
    '2231000': 'Semente de Coco',
    '2223000': 'Semente de Algodão',
    '2232000': 'Semente de Amêndoa de Palma',
    '2221000': 'Semente de Amendoim',
    '2226000': 'Semente de Colza',
    '2222000': 'Semente de Soja',
    '2222001': 'Semente de Soja (Local)',
    '2224000': 'Semente de Girassol',
    '0585100': 'Suco de Laranja',
    '0571120': 'Laranjas, Frescas',
    '0579309': 'Pêssegos e Nectarinas, Frescos',
    '0579220': 'Pêras, Frescas',
    '0577907': 'Pistaches, Base com Casca',
    '0114200': 'Aves, Carne, Frangos',
    '0422110': 'Arroz, Beneficiado',
    '0451000': 'Centeio',
    '0459200': 'Sorgo',
    '0612000': 'Açúcar, Centrífugo',
    '0571220': 'Tangerinas/Mexericas, Frescas',
    '0577901': 'Nozes, Base com Casca',
    '0410000': 'Trigo'
}

country_dict = {
    'AF': 'Afeganistão',
    'AL': 'Albânia',
    'AG': 'Argélia',
    'AO': 'Angola',
    'AC': 'Antígua e Barbuda',
    'AR': 'Argentina',
    'AM': 'Armênia',
    'AS': 'Austrália',
    'AU': 'Áustria',
    'AJ': 'Azerbaijão',
    'BF': 'Bahamas',
    'BA': 'Bahrein',
    'BG': 'Bangladesh',
    'BB': 'Barbados',
    'BO': 'Belarus',
    'S8': 'Bélgica (sem Luxemburgo)',
    'BE': 'Bélgica-Luxemburgo',
    'BH': 'Belize',
    'DM': 'Benin',
    'BD': 'Bermudas',
    'BT': 'Butão',
    'BL': 'Bolívia',
    'BK': 'Bósnia e Herzegovina',
    'BC': 'Botsuana',
    'BR': 'Brasil',
    'BX': 'Brunei',
    'BU': 'Bulgária',
    'UV': 'Burkina Faso',
    'BM': 'Birmânia',
    'BY': 'Burundi',
    'CV': 'Cabo Verde',
    'CB': 'Camboja',
    'CM': 'Camarões',
    'CA': 'Canadá',
    'CT': 'República Centro-Africana',
    'CD': 'Chade',
    'CI': 'Chile',
    'CH': 'China',
    'CO': 'Colômbia',
    'CN': 'Comores',
    'CF': 'República do Congo',
    'CG': 'República Democrática do Congo',
    'CS': 'Costa Rica',
    'IV': "Costa do Marfim",
    'HR': 'Croácia',
    'CU': 'Cuba',
    'CY': 'Chipre',
    'EZ': 'República Tcheca',
    'DA': 'Dinamarca',
    'DJ': 'Djibuti',
    'DO': 'Dominica',
    'DR': 'República Dominicana',
    'EC': 'Equador',
    'EG': 'Egito',
    'ES': 'El Salvador',
    'EK': 'Guiné Equatorial',
    'ER': 'Eritreia',
    'EN': 'Estônia',
    'WZ': 'Eswatini',
    'ET': 'Etiópia',
    'E2': 'UE-15',
    'E3': 'UE-25',
    'E4': 'União Europeia',
    'FA': 'Ilhas Malvinas',
    'FO': 'Ilhas Faroe',
    'FJ': 'Fiji',
    'FI': 'Finlândia',
    'CZ': 'Antiga Tchecoslováquia',
    'YO': 'Antiga Iugoslávia',
    'FT': 'França Equatorial e do Sul',
    'FR': 'França',
    'FG': 'Guiana Francesa',
    'FP': 'Polinésia Francesa',
    'Y2': 'Antilhas Francesas',
    'GB': 'Gabão',
    'GA': 'Gâmbia',
    'GZ': 'Faixa de Gaza',
    'GG': 'Geórgia',
    'GC': 'Alemanha Oriental',
    'GM': 'Alemanha',
    'GE': 'Alemanha Ocidental',
    'GH': 'Gana',
    'GI': 'Gibraltar',
    'GN': 'Ilhas Gilbert e Ellice',
    'GR': 'Grécia',
    'GL': 'Groenlândia',
    'GJ': 'Granada',
    'GP': 'Guadalupe',
    'GT': 'Guatemala',
    'GU': 'Guiné',
    'PU': 'Guiné-Bissau',
    'GY': 'Guiana',
    'HA': 'Haiti',
    'HO': 'Honduras',
    'HK': 'Hong Kong',
    'HU': 'Hungria',
    'IC': 'Islândia',
    'IN': 'Índia',
    'ID': 'Indonésia',
    'IR': 'Irã',
    'IZ': 'Iraque',
    'EI': 'Irlanda',
    'IS': 'Israel',
    'IT': 'Itália',
    'JM': 'Jamaica',
    'JA': 'Japão',
    'JO': 'Jordânia',
    'KZ': 'Cazaquistão',
    'KE': 'Quênia',
    'KN': 'Coreia do Norte',
    'KS': 'Coreia do Sul',
    'KV': 'Kosovo',
    'KU': 'Kuwait',
    'KG': 'Quirguistão',
    'LA': 'Laos',
    'LG': 'Letônia',
    'LE': 'Líbano',
    'LT': 'Lesoto',
    'LI': 'Libéria',
    'LY': 'Líbia',
    'LH': 'Lituânia',
    'LU': 'Luxemburgo',
    'MC': 'Macau',
    'MA': 'Madagascar',
    'MI': 'Malawi',
    'MY': 'Malásia',
    'MV': 'Maldivas',
    'ML': 'Mali',
    'MT': 'Malta',
    'MB': 'Martinica',
    'MR': 'Mauritânia',
    'MP': 'Maurício',
    'MX': 'México',
    'MD': 'Moldávia',
    'MG': 'Mongólia',
    'MJ': 'Montenegro',
    'MO': 'Marrocos',
    'MZ': 'Moçambique',
    'WA': 'Namíbia',
    'NP': 'Nepal',
    'NL': 'Holanda',
    'NA': 'Antilhas Holandesas',
    'NC': 'Nova Caledônia',
    'NZ': 'Nova Zelândia',
    'NU': 'Nicarágua',
    'NG': 'Níger',
    'NI': 'Nigéria',
    'MK': 'Macedônia do Norte',
    'NO': 'Noruega',
    'MU': 'Omã',
    'ZZ': 'Outro',
    'PK': 'Paquistão',
    'PN': 'Panamá',
    'PP': 'Papua Nova Guiné',
    'PA': 'Paraguai',
    'PE': 'Peru',
    'RP': 'Filipinas',
    'PL': 'Polônia',
    'PO': 'Portugal',
    'RQ': 'Porto Rico',
    'QA': 'Catar',
    'RE': 'Reunião',
    'RO': 'Romênia',
    'RS': 'Rússia',
    'RW': 'Ruanda',
    'WS': 'Samoa',
    'TP': 'São Tomé e Príncipe',
    'SA': 'Arábia Saudita',
    'SG': 'Senegal',
    'RB': 'Sérvia',
    'SR': 'Sérvia e Montenegro',
    'SE': 'Seychelles',
    'SL': 'Serra Leoa',
    'SN': 'Singapura',
    'LO': 'Eslováquia',
    'SI': 'Eslovênia',
    'BP': 'Ilhas Salomão',
    'SO': 'Somália',
    'SF': 'África do Sul',
    'OD': 'Sudão do Sul',
    'SP': 'Espanha',
    'CE': 'Sri Lanka',
    'SC': 'São Cristóvão e Nevis',
    'ST': 'Santa Lúcia',
    'VC': 'São Vicente e Granadinas',
    'SU': 'Sudão',
    'NS': 'Suriname',
    'SW': 'Suécia',
    'SZ': 'Suíça',
    'SY': 'Síria',
    'TW': 'Taiwan',
    'TI': 'Tajiquistão',
    'TZ': 'Tanzânia',
    'TH': 'Tailândia',
    'TO': 'Togo',
    'TN': 'Tonga',
    'TD': 'Trinidad e Tobago',
    'TS': 'Tunísia',
    'TU': 'Turquia',
    'TX': 'Turcomenistão',
    'UG': 'Uganda',
    'UP': 'Ucrânia',
    'UR': 'União Soviética',
    'TC': 'Emirados Árabes Unidos',
    'UK': 'Reino Unido',
    'US': 'Estados Unidos',
    'UY': 'Uruguai',
    'UZ': 'Uzbequistão',
    'NH': 'Vanuatu/Nova Hébridas',
    'VE': 'Venezuela',
    'VM': 'Vietnã',
    'VO': 'Ilhas Virgens dos EUA',
    'YM': 'Iêmen',
    'YS': 'Iêmen (Aden)',
    'YE': 'Iêmen (Sanaa)',
    'YU': 'Iugoslávia',
    'ZA': 'Zâmbia',
    'RH': 'Zimbábue'
}

name_attribute = {
    1: "Área Plantada",
    4: "Área Colhida",
    5: "Captura para Redução",
    6: "Vacass em Lactação",
    7: "Esmagamento",
    10: "Esmagamento Total de Uvas",
    13: "Entrega aos Processadores",
    16: "Árvores Totais",
    17: "Árvores Produtoras",
    19: "Árvores Não Produtoras",
    20: "Estoque Inicial",
    22: "Estoque Inicial de Porcas",
    23: "Estoque Inicial de Vacas Leiteiras",
    24: "Estoque Inicial (Aplicação de Controle)",
    25: "Estoque Inicial de Vacas de Corte",
    26: "Estoque Inicial (Outros)",
    28: "Produção",
    29: "Produção de Arábica",
    30: "Produção de Açúcar de Beterraba",
    31: "Produção Comercial",
    32: "Produção de Leite de Vacas",
    33: "Peso de Vendas na Fazenda",
    34: "Produção de Filtro",
    40: "Prod. de Uvas para Vinho",
    43: "Produção de Açúcar de Cana",
    47: "Produção Não Comercial",
    48: "Produção não de Filtro",
    49: "Outra Produção de Leite",
    51: "Prod. de Uvas de Mesa",
    53: "Produção de Robusta",
    54: "Produção Bruta",
    56: "Outra Produção",
    57: "Importações",
    58: "Importações de Feijão",
    62: "Importações Intra-UE",
    63: "Minhas Importações dos EUA",
    64: "Importações Brutas",
    65: "Importações de Folhas dos EUA",
    70: "Minhas Importações da UE",
    71: "Outras Importações",
    74: "Imp. Refinado (Valor Bruto)",
    75: "Imp. de Torrefação e Moagem",
    78: "Imp. CY",
    81: "Imp. TY",
    82: "Imp. Solúvel",
    83: "Imp. CY dos EUA",
    84: "Imp. TY dos EUA",
    86: "Oferta Total",
    87: "Exp. CY para EUA",
    88: "Exportações",
    89: "Exportações Brutas",
    90: "Exportações de Feijão",
    94: "Exp. Intra UE",
    95: "Exp. Intra-UE",
    97: "Minhas Exportações para a UE",
    99: "Exp. Refinado (Valor Bruto)",
    104: "Outras Exportações",
    107: "Exp. de Torrefação e Moagem",
    110: "Exp. CY",
    113: "Exp. TY",
    114: "Exp. Solúvel",
    116: "Abate (Referência)",
    117: "Abate Total",
    118: "Abate de Vacas",
    120: "Inventário (Referência)",
    121: "Abate de Porcas",
    122: "Abate de Bezerros",
    124: "Outro Abate",
    125: "Consumo Doméstico",
    126: "Desaparecimento Total",
    128: "Consumo Dom. de Folhas",
    129: "Consumo Doméstico (Aplicação de Controle)",
    130: "Consumo Doméstico de Ração",
    131: "Uso de Consumo Doméstico de Líquidos",
    132: "Para Processamento",
    133: "Consumo Dom. Fresco",
    135: "Consumo Dom. Fresco",
    138: "Consumo Humano",
    139: "Consumo Humano Doméstico",
    140: "Consumo Industrial Doméstico",
    141: "Consumo Dom. de Torrado e Moído",
    142: "Uso Doméstico",
    143: "Utilização para Açúcar",
    145: "Consumo Doméstico (Outros)",
    147: "Consumo de Fábrica",
    149: "Consumo Alimentar Dom. Cons.",
    150: "Perda",
    151: "Outro Desaparecimento",
    152: "Outro Uso, Perdas",
    154: "Consumo Solúvel Dom.",
    155: "Consumo de Folhas dos EUA Dom.",
    157: "Utilização para Álcool",
    158: "Consumo Dom. de Ração",
    161: "Desperdício de Ração Dom. Cons.",
    167: "Outro Consumo Estrangeiro",
    169: "Retirada do Mercado",
    172: "Perda e Residual",
    173: "Desaparecimento Total",
    174: "Uso Total",
    175: "Utilização Total",
    176: "Estoque Final",
    177: "Estoques Finais (Aplicação de Controle)",
    178: "Distribuição Total",
    179: "Estoques Finais (Outros)",
    181: "Taxa de Extração, 999.9999",
    182: "Taxa de Moagem (.9999)",
    183: "Proporção de Sementes para Algodão",
    184: "Rendimento",
    192: "Consumo de EFI",
    194: "SME",
    195: "Estoques para Uso",
    196: "Produção Exportável",
    198: "Equilíbrio",
    199: "Saldo de Inventário",
    200: "Alteração de Inventário",
    201: "Alteração de Importação",
    202: "Alteração de Exportação",
    203: "Alteração de Consumo",
    204: "Alteração de Produção",
    205: "Alteração de Porcas",
    206: "Alteração de Vacas",
    207: "Produção para Vacas",
    208: "Produção para Porcas",
    209: "Abate para Inventário",
    210: "Pesos",
    211: "População",
    212: "Consumo Per Capita",
    213: "Abate para Oferta Total",
    214: "Importações Percentual de Consumo",
    215: "Exportações Percentual de Produção",
    220: "Variação Anual % no Consumo Per Capita",
    223: "Estoques para Uso (Meses)"
    
}

unidades_descricoes = {
    1: "1000 ALQUEIRES",
    2: "1000 SACOS DE 60 KG",
    3: "1000 COLÔNIAS",
    4: "1000 HECTARES",
    5: "1000 CABEÇAS",
    6: "1000 HECTOLITROS",
    7: "1000 TONELADAS CWE",
    8: "1000 TONELADAS",
    9: "1000 PEÇAS",
    10: "1000 ÁRVORES",
    11: "Fração Decimal",
    12: "HECTARES",
    13: "HECTARES",
    14: "QUILOGRAMAS",
    15: "MIL CABEÇAS",
    16: "MIL PEÇAS",
    17: "MILHÕES DE ÁRVORES",
    18: "TONELADAS EQUIVALENTES EM BRUTO",
    19: "TONELADAS EQUIVALENTES EM PESO",
    20: "TONELADAS DE RE",
    21: "TONELADAS",
    22: "TONELADAS, PESO LÍQUIDO",
    23: "PORCENTAGEM",
    24: "RAZÃO",
    25: "1000 METROS CÚBICOS",
    26: "TONELADAS POR HECTARE",
    27: "1000 FARDOS DE 480 LB.",
    28: "FARDOS POR HECTARE",
    29: "QUILOGRAMAS POR HECTARE",
    30: "ACRES",
    31: "ALQUEIRES",
    32: "QUINTAIS",
    33: "TAXA DE MOAGEM",
    34: "ALQUEIRES POR TONELADA",
    35: "TAXA DE MOAGEM DE IMPORTAÇÃO",
    36: "ALQUEIRES",
    37: "TONELADAS CURTAS",
    38: "MILHÕES DE LIBRAS",
    39: "BILHÕES DE LIBRAS",
    40: "CABEÇAS",
    41: "PESSOAS",
    42: "MESES"
}